site_name: Cyber Security Notes

nav:
  - Profile: index.md
  - Basic Knowledge:
      - Web Browser Info: basic_knowledge/web_browser_info.md
      - Linux Commands: basic_knowledge/linux_command.md

  - SOC Analyst L1:
    - Road Map: soc_analyst_l1/road_map.md
    
  - Important Topics:
      - Topics List: important_topics/topic_list.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - navigation.path
    - navigation.instant

markdown_extensions:
  - toc:
      toc_depth: 3

plugins:
  - search

extra_css:
  - core/statics/custom.css
